---
- name: Ensure MongoDB group exists
  group:
    name: "{{ mongodb_group }}"
    state: present

- name: Ensure MongoDB user exists
  user:
    name: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    createhome: no
    shell: /usr/sbin/nologin

- name: Ensure MongoDB system log directory exists
  file:
    path: "{{ mongodb_systemlog_dir }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: '0755'

- name: Ensure MongoDB data directory exists
  file:
    path: "{{ mongodb_data_dir }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: '0755'


    