---
- name: Update apt package list
  ansible.builtin.apt:
    update_cache: yes

- name: Install gnupg and curl
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
    state: present

- name: Add MongoDB GPG key
  ansible.builtin.apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present

- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-{{ mongodb_version }}.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/{{ mongodb_version }} multiverse"
    filename: "mongodb-org-{{ mongodb_version }}"

- name: Update apt package list after adding MongoDB repo
  ansible.builtin.apt:
    update_cache: yes

- name: Install MongoDB packages
  ansible.builtin.apt:
    name: "{{ mongodb_packages }}"
    state: present

