---
- name: Installing Required Packages and MongoDB
  ansible.builtin.include_tasks: mongoDB_installation.yml
  
- name: configuring user,group,log_directory & data_directory   # Setting up Mongodb service & log Directory
  ansible.builtin.include_tasks: mongoDB_config.yml

- name: setup service file for MongoDb
  ansible.builtin.include_tasks: mongoDB_service.yml
  
- name: check if it is standalone server or not
  ansible.builtin.include_tasks: standalone_check.yml

- name: setup auth in nodes
  ansible.builtin.include_tasks: mongoDB_setup_auth.yml

- name: Openssl Certification creation
  ansible.builtin.include_tasks: openssl_cert.yml
  when: Openssl_cert == True

- name: Domain regstrar SSL
  ansible.builtin.include_tasks: domain_cert.yml
  when: Openssl_cert == False

- name: Enabling mongodb Cluster
  ansible.builtin.include_tasks: mongo_cluster_setup.yml