---
- name: Installing prerequesties for Mongodb
  ansible.builtin.include_tasks: prerequesties.yml
  when: standalone == True or mongodb_cluster == True

- name: Installing Required Packages and Mongodb
  ansible.builtin.include_tasks: mongodb_installation.yml
  when: standalone == True or mongodb_cluster == True

- name: Configuring user,group,log_directory ,data_directory   & Systemd Service
  ansible.builtin.include_tasks: mongodb_config.yml
  when: standalone == True or mongodb_cluster == True

# - name: Setup service file for Mongodb
#   ansible.builtin.include_tasks: mongoDB_service.yml
#   when: standalone == True or mongodb_cluster == True 

- name: Setup auth in slave nodes
  ansible.builtin.include_tasks: mongoDB_setup_auth.yml
  when: mongodb_cluster == True

- name: Openssl Certification creation 
  ansible.builtin.include_tasks: openssl_cert.yml
  when: openssl_cert == True and mongodb_cluster == True

- name: implement Domain registrar SSL
  ansible.builtin.include_tasks: domain_cert.yml
  when: openssl_cert == False and mongodb_cluster == True

- name: Enabling mongodb Cluster
  ansible.builtin.include_tasks: mongo_cluster_setup.yml
  when: mongodb_cluster == True

- name: Add slaves in mongodb Cluster
  ansible.builtin.include_tasks: add_slave.yml
  when: mongodb_cluster == True

- name: Remove slaves from mongodb Cluster
  ansible.builtin.include_tasks: remove_slave.yml
  when: mongodb_cluster == True
