---
- name: Installing prerequesties
  ansible.builtin.include_tasks: prerequesties.yml

- name: Installing Required Packages and MongoDB
  ansible.builtin.include_tasks: mongoDB_installation.yml

- name: Configuring user,group,log_directory & data_directory   # Setting up Mongodb service & log Directory
  ansible.builtin.include_tasks: mongoDB_config.yml

- name: Setup service file for MongoDb
  ansible.builtin.include_tasks: mongoDB_service.yml

- name: Check if it is standalone server or not
  ansible.builtin.include_tasks: standalone_check.yml

- name: Setup auth in nodes
  ansible.builtin.include_tasks: mongoDB_setup_auth.yml

- name: Openssl Certification creation
  ansible.builtin.include_tasks: openssl_cert.yml
  when: Openssl_cert == True

- name: Domain regstrar SSL
  ansible.builtin.include_tasks: domain_cert.yml
  when: Openssl_cert == False

- name: Enabling mongodb Cluster
  ansible.builtin.include_tasks: mongo_cluster_setup.yml

- name: Add slaves
  ansible.builtin.include_tasks: add_slave.yml

- name: Remove slaves
  ansible.builtin.include_tasks: remove_slave.yml
