---
- name: installing mongoDB
  ansible.builtin.include_tasks: install.yml
- name: configuring user,group,log_director & data_directory 
  ansible.builtin.include_tasks: config.yml
- name: setup service file for MongoDb
  ansible.builtin.include_tasks: service.yml
- name: check if it is standalone server or not 
  ansible.builtin.include_tasks: standalone_check.yml

- name: replicate slave nodes
  ansible.builtin.include_tasks: replicate.yml
- name: creat users for monoDB
  ansible.builtin.include_tasks: monoDB.user_creation.yml
- name: setup auth in nodes
  ansible.builtin.include_tasks: setup_auth.yml
