---
- name: configure | Create mongodb group
  ansible.builtin.group:
    name: "{{ mongo_service_group }}"
    state: present
  when: inventory_hostname in groups['mongo_master'] + groups['mongo_slave']

- name: configure | Create mongodb user
  ansible.builtin.user:
    name: "{{ mongo_service_user }}"
    group: "{{ mongo_service_group }}"
    state: present
  when: inventory_hostname in groups['mongo_master'] + groups['mongo_slave']

- name: configure | Create systemlog dir if missing
  ansible.builtin.file:
    state: directory
    dest: "{{ mongo_systemlog_path | dirname }}"
    owner: "{{ mongo_service_user }}"
    group: "{{ mongo_service_group }}"
    mode: "0755"
  when: inventory_hostname in groups['mongo_master'] + groups['mongo_slave']

- name: configure | Check systemlog file exists
  ansible.builtin.stat:
    path: "{{ mongo_systemlog_path }}"
  register: logfile_stat

- name: configure | Check if systemlog file already exists
  ansible.builtin.stat:
    path: "{{ mongo_systemlog_path }}"
  register: systemlog_file

- name: configure | Create systemlog file if missing
  ansible.builtin.file:
    state: touch
    dest: "{{ mongo_systemlog_path }}"
    owner: "{{ mongo_service_user }}"
    group: "{{ mongo_service_group }}"
    mode: "0644"
  when: not systemlog_file.stat.exists

- name: configure | Place authentication key on each node
  ansible.builtin.copy:
    dest: /etc/{{ mongo_authentication_keyname }} 
    content: "{{ mongo_authentication_key }}"
    mode: "0400"
    owner: "{{ mongo_service_user }}"
    group: "{{ mongo_service_group }}"
  when: authentication_enabled and replication_enabled

- name: configure | Mongo Configuration Setup
  ansible.builtin.template:
    src: mongo_init_conf.j2
    dest: /etc/mongod.conf
    owner: "{{ mongo_service_user }}"
    group: "{{ mongo_service_group }}"
    mode: "0644"
  notify:
    - Mongodb_restart

- name: configure | Flush all handlers at this point
  ansible.builtin.meta: flush_handlers