---
- name: Update apt package list
  ansible.builtin.apt:
    update_cache: true

- name: Install gnupg and curl
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present

- name: Import MongoDB GPG key
  apt_key:
    url: "{{ mongo_key_url }}"
    state: present
    validate_certs: yes
    keyring: "{{ mongodb_gpg_keyring }}"

- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: '{{ mongo_repo_url }}'
    filename: "mongodb-org-{{ mongodb_version }}"

- name: Update apt package list after adding MongoDB repo
  ansible.builtin.apt:
    update_cache: true

- name: Install MongoDB packages
  ansible.builtin.apt:
    name: "{{ mongodb_packages }}"
    state: present
  become: true
  notify:
    - Mongodb_restart
