---
- name: Remove Mongodb Slave |  Place a script on master node to remove slave
  ansible.builtin.template:
    src: remove_slave_init.j2
    dest: /tmp/remove_slave_init.js
    mode: "0666"
  when: inventory_hostname in groups['mongo_master']

- name: Removing Mongodb Slave
  ansible.builtin.shell: |
    mongosh --tls --tlsCAFile {{ ca_directory_path }}/{{ ca_cert_pem_name }} \
    --host {{ master_ip }}:27017 \
    --tlsCertificateKeyFile {{ mongodb_ssl_directory }}/{{ concatenate_mongodb_pem_file }} \
    --tlsCertificateKeyFilePassword {{ secret_ca_passphrase }} \
    -u {{ mongo_root_admin_name }} -p {{ mongo_root_admin_pwd }} < /tmp/remove_slave_init.js
  when: inventory_hostname in groups['mongo_master']
  register: replication_result_remove_slave

- name: Show replication result for additional Slave added
  ansible.builtin.debug:
    var: replication_result_remove_slave