---
- name: Create MongoDB service file from template
  template:
    src: mongod.service.j2
    dest: /etc/systemd/system/mongod.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart MongoDB

- name: Enable and start MongoDB service
  service:
    name: mongod
    enabled: yes
    state: started

