---
- name: Reload_systemd
  ansible.builtin.systemd:
    daemon_reload: "yes"

- name: Mongodb_restart
  ansible.builtin.service:
    name: "{{ mongo_service_name }}"
    state: restarted

- name: Wait_till_mongodb_started
  ansible.builtin.wait_for:
    host: "{{ item }}"
    port: "{{ mongo_port }}"
    timeout: 120
  with_items:
    - "{{ groups['mongo_master'] | list }}"
    - "{{ groups['mongo_slave'] | list }}"

- name: Wait_till_mongodb_started_on_localhost
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: "{{ mongo_port }}"
    delay: 5
    timeout: 120