---
- name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: mongod
  listen: reload_service_systemd

- name: Enable and start MongoDB service
  ansible.builtin.systemd_service:
    name: mongod
    enabled: true
    state: started
  listen: enable_start_mongo

- name: Restart MongoDB
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
  listen: Mongodb_restart

- name: Wait_till_mongodb_started_on_localhost
  ansible.builtin.wait_for:
    host: "127.0.0.1"
    port: "{{ mongo_port }}"
    delay: 5
    timeout: 120
