---
- name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: mongod
  listen: reload_service_systemd

- name: Enable and start MongoDB service
  service:
    name: mongod
    enabled: yes
    state: started
  listen: enable_start_mongo
 
- name: Restart MongoDB
  service:
    name: mongod
    state: restarted
  listen: Mongodb_restart

